/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIView;

import BLL.Consumer;
import BLL.Delivery;
import DAL.DeliveryRepository;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OEM
 */
public class ConfrimDeliveryUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfrimDeliveryUser
     */
    private int TicketNr = 1000;
    DeliveryRepository dr = new DeliveryRepository();
    SelectConsumers sc = new SelectConsumers();
    Consumer con = sc.getConsumatori();
    public ConfrimDeliveryUser() {
        initComponents();
        addRowToTable();
        calculo();
        TicketNr++;
    }
   
     
    ArrayList<Double> listaa = null;
        private void addRowToTable(){
          DefaultTableModel model = (DefaultTableModel)table.getModel();
          ArrayList <String> lista = CreatesDeliveryUser.getOrderChoose();
          ArrayList<Integer> list = CreatesDeliveryUser.listaSasia;
          listaa = CreatesDeliveryUser.listaPrice;
          Object rowData[] = new Object[3];
          for(int i=0;i<lista.size();i++){
              rowData[0] =lista.get(i);
              rowData[1] = list.get(i);
              rowData[2] = listaa.get(i);
              model.addRow(rowData);
          }
        }
        
        double shuma = 0;
        private void calculo(){
            double tvsh = 0.18;
            listaa = CreatesDeliveryUser.listaPrice;
            for(Double b : listaa){
                shuma+=b;
            }
            double paTVSH = shuma - (shuma*tvsh);
            String str = String.format("%.2f", paTVSH);
            qmimiMeTVSHField.setText(String.valueOf(shuma));
            qmimiPaTVSHField.setText(str);
            qmimiField.setText(String.valueOf(shuma)); 
            ticketNrField.setText(String.valueOf(TicketNr));
        }
        
        private void clear(){
            qmimiMeTVSHField.setText("");
            qmimiPaTVSHField.setText("");
            qmimiField.setText("");
            ticketNrField.setText("");
            table.clearSelection();
            ecCheckBox.setSelected(false);
            table.removeAll();
        }
        
        private String metodaPageses(){
            String menyra = " ";
            if(ecCheckBox.isSelected()){
                menyra = "EC";
            }else{
                menyra = "Cash";
            }
            
            return menyra;
        }
        
        private boolean check(){
            if(ecCheckBox.isSelected()){
                return true;
            }
            return false;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        ticketNrField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        qmimiMeTVSHField = new javax.swing.JTextField();
        qmimiPaTVSHField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qmimiField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        confrimButton = new javax.swing.JButton();
        ecCheckBox = new javax.swing.JCheckBox();
        cashCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(830, 590));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ticket Nr.");

        ticketNrField.setEditable(false);
        ticketNrField.setText("3");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Sasia", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel2.setText("Qmimi me TVSH");

        qmimiMeTVSHField.setEditable(false);
        qmimiMeTVSHField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qmimiMeTVSHFieldActionPerformed(evt);
            }
        });

        qmimiPaTVSHField.setEditable(false);

        jLabel3.setText("Qmimi pa TVSH");

        qmimiField.setEditable(false);

        jLabel4.setText("Qmimi");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        confrimButton.setText("Confirm");
        confrimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confrimButtonActionPerformed(evt);
            }
        });

        ecCheckBox.setText("EC");

        cashCheckBox.setText("Cash");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PAYMENT INFORMATION");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ticketNrField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(qmimiMeTVSHField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(qmimiPaTVSHField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(qmimiField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cancelButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(confrimButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ecCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cashCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(cancelButton)
                        .addGap(212, 212, 212)
                        .addComponent(confrimButton))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ticketNrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel10)
                                .addGap(79, 79, 79)
                                .addComponent(ecCheckBox))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qmimiField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qmimiPaTVSHField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qmimiMeTVSHField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5)
                        .addComponent(cashCheckBox)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketNrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(ecCheckBox)
                                    .addComponent(cashCheckBox))
                                .addGap(36, 36, 36)))
                        .addComponent(qmimiMeTVSHField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qmimiPaTVSHField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qmimiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confrimButton)
                    .addComponent(cancelButton))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void qmimiMeTVSHFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qmimiMeTVSHFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qmimiMeTVSHFieldActionPerformed

    private void confrimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimButtonActionPerformed
        // TODO add your handling code here:
        if(check()){
            try{
            Delivery d = new Delivery();
            d.setTicketNr(TicketNr);
            d.setPrice(shuma);
            d.setConsumerID(con);
            d.setPaymentMethod(metodaPageses());
            dr.create(d);
            JOptionPane.showMessageDialog(this,"U krijua Delivery me sukses");
            clear();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this,"Ju lutem selektoni menyren e pageses");
        }    
        
    }//GEN-LAST:event_confrimButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox cashCheckBox;
    private javax.swing.JButton confrimButton;
    private javax.swing.JCheckBox ecCheckBox;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField qmimiField;
    private javax.swing.JTextField qmimiMeTVSHField;
    private javax.swing.JTextField qmimiPaTVSHField;
    private javax.swing.JTable table;
    private javax.swing.JTextField ticketNrField;
    // End of variables declaration//GEN-END:variables
}
