/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIView;

import BLL.Delivery;
import BLL.Ordery;
import DAL.CrudFormException;
import DAL.DeliveryRepository;
import DAL.OrderyRepository;
import GUIModel.DeliveryTableModel;
import GUIModel.OrderyTableModel;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.KeyStroke;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author OEM
 */
public class ListsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ListsAdmin
     */
    OrderyRepository or = new OrderyRepository();
    OrderyTableModel odtm = new OrderyTableModel();
    DeliveryRepository dr = new DeliveryRepository();
    DeliveryTableModel dtm = new DeliveryTableModel();
    
   
    public ListsAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        loadTableOrdery();
        loadTableDelivery();
    }
    
    private void loadTableOrdery(){
        try{
            List<Ordery> lista = or.findAll();
            odtm.addListOrdery(lista);
            table2.setModel(odtm);
            odtm.fireTableDataChanged();
        }catch(CrudFormException ex){
            Logger.getLogger(BreakfastAdmin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    private void loadTableDelivery(){
        try{
            List<Delivery> lista = dr.findAll();
            dtm.addListDelivery(lista);
            table1.setModel(dtm);
            odtm.fireTableDataChanged();
        }catch(CrudFormException ex){
            Logger.getLogger(BreakfastAdmin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketsDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        listsTicketButton = new javax.swing.JButton();
        breakfastButton = new javax.swing.JButton();
        saladButton = new javax.swing.JButton();
        burgerButton = new javax.swing.JButton();
        drinkButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticketsDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("List's of Ticktes");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table1);

        ticketsDesktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ticketsDesktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ticketsDesktopPane.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ticketsDesktopPane.setLayer(label, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ticketsDesktopPaneLayout = new javax.swing.GroupLayout(ticketsDesktopPane);
        ticketsDesktopPane.setLayout(ticketsDesktopPaneLayout);
        ticketsDesktopPaneLayout.setHorizontalGroup(
            ticketsDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketsDesktopPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361))
            .addGroup(ticketsDesktopPaneLayout.createSequentialGroup()
                .addGroup(ticketsDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketsDesktopPaneLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ticketsDesktopPaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ticketsDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        ticketsDesktopPaneLayout.setVerticalGroup(
            ticketsDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketsDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        listsTicketButton.setText("Lists of Tickets");
        listsTicketButton.setMargin(null);
        listsTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listsTicketButtonActionPerformed(evt);
            }
        });
        jPanel1.add(listsTicketButton);

        breakfastButton.setText("Breakfast");
        breakfastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfastButtonActionPerformed(evt);
            }
        });
        jPanel1.add(breakfastButton);

        saladButton.setText("Salad");
        saladButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saladButton);

        burgerButton.setText("Burger");
        burgerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(burgerButton);

        drinkButton.setText("Drink");
        drinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(drinkButton);

        createUserButton.setText("Create User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createUserButton);

        jButton1.setText("GenerateScript");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketsDesktopPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ticketsDesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listsTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listsTicketButtonActionPerformed
        // TODO add your handling code here:
        ticketsDesktopPane.removeAll();
        this.setVisible(false);
        ListsAdmin la = new ListsAdmin();
        la.setVisible(true);
    }//GEN-LAST:event_listsTicketButtonActionPerformed

    private void breakfastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastButtonActionPerformed
        // TODO add your handling code here:
        ticketsDesktopPane.remove(0);
        BreakfastAdmin ba = new BreakfastAdmin();
        ticketsDesktopPane.add(ba);
        ba.show();
    }//GEN-LAST:event_breakfastButtonActionPerformed

    private void saladButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladButtonActionPerformed
        // TODO add your handling code here:
        ticketsDesktopPane.remove(0);
        SaladAdmin sa = new SaladAdmin();
        ticketsDesktopPane.add(sa);
        sa.show();
    }//GEN-LAST:event_saladButtonActionPerformed

    private void burgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerButtonActionPerformed
        // TODO add your handling code here:
          ticketsDesktopPane.remove(0);
        BurgerAdmin ba = new BurgerAdmin();
        ticketsDesktopPane.add(ba);
        ba.show();
    }//GEN-LAST:event_burgerButtonActionPerformed

    private void drinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkButtonActionPerformed
        // TODO add your handling code here:
          ticketsDesktopPane.remove(0);
        DrinksAdmin da = new DrinksAdmin();
        ticketsDesktopPane.add(da);
        da.show();
    }//GEN-LAST:event_drinkButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // TODO add your handling code here:
          ticketsDesktopPane.remove(0);
        CreateUserAdmin cua  = new CreateUserAdmin();
        ticketsDesktopPane.add(cua);
        cua.show();
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        LogIn ln = new LogIn();
        ln.setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GenerateScript gs = new GenerateScript();
        ticketsDesktopPane.add(gs);
        gs.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListsAdmin().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton breakfastButton;
    private javax.swing.JButton burgerButton;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton drinkButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JButton listsTicketButton;
    private javax.swing.JButton saladButton;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JDesktopPane ticketsDesktopPane;
    // End of variables declaration//GEN-END:variables
}
