/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIView;

import BLL.Consumer;
import DAL.ConsumerRepository;
import DAL.CrudFormException;
import GUIModel.ConsumerComboBoxModel;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author OEM
 */
public class SelectConsumers extends javax.swing.JFrame {

    /**
     * Creates new form SelectConsumers
     */
    ConsumerRepository cr = new ConsumerRepository();
    ConsumerComboBoxModel ccbm = new ConsumerComboBoxModel();
    static Consumer c;
    
    public SelectConsumers() {
        initComponents();
        setLocationRelativeTo(null);
        loadComboBox(); 
    }
    
    private void loadComboBox(){
        try{
            List<Consumer> lista = cr.findAll();
            ccbm.addList(lista);
            CMBConsumer.setModel(ccbm);
            CMBConsumer.repaint();
        }catch(CrudFormException ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
    
    private boolean check(){
        if(firstNameField.getText() == null || firstNameField.getText().trim().isEmpty()){
            return false;
        }
        if(lastNameField.getText() == null || lastNameField.getText().trim().isEmpty()){
            return false;
        }
        if(cityField.getText() == null || cityField.getText().trim().isEmpty() ){
            return false;
        }
        if(emailField.getText() == null || emailField.getText().trim().isEmpty()){
            return false;
        }
        if (adressField.getText() == null || adressField.getText().trim().isEmpty()) {
            return false;
        }
        if (codeField.getText() == null || codeField.getText().isEmpty()) {
            return false;
        }
        if(numberField.getText() == null || numberField.getText().isEmpty()){
            return false;
        }
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adressField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CMBConsumer = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        selectConsumatorButton = new javax.swing.JButton();
        placeDeliveryButton = new javax.swing.JButton();
        confirmDeliveryButton = new javax.swing.JButton();
        selectDeliveryOrderyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(857, 671));

        mainDesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        mainDesktopPane.setPreferredSize(new java.awt.Dimension(700, 650));

        jLabel6.setText("City");

        jLabel5.setText("Adress");

        jLabel4.setText("Last Name");

        jLabel3.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Select Consumator");

        submitButton.setText("Submit ");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Email");

        jLabel8.setText("Contact Nr.");

        jLabel7.setText("Postal Code");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Create Consumator");

        CMBConsumer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mainDesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(codeField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(numberField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(cityField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(adressField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(emailField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(lastNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(firstNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(submitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainDesktopPane.setLayer(CMBConsumer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                                        .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(36, 36, 36))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(23, 23, 23)
                                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(firstNameField)
                                    .addComponent(cityField)
                                    .addComponent(emailField)
                                    .addComponent(adressField)
                                    .addComponent(codeField)
                                    .addComponent(numberField)))
                            .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel2))))
                    .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainDesktopPaneLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(CMBConsumer, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDesktopPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDesktopPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CMBConsumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addGap(42, 42, 42)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        selectConsumatorButton.setText("SelectConsumator");

        placeDeliveryButton.setText("Place Delivery");
        placeDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeDeliveryButtonActionPerformed(evt);
            }
        });

        confirmDeliveryButton.setText("Confirm Delivery");
        confirmDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeliveryButtonActionPerformed(evt);
            }
        });

        selectDeliveryOrderyButton.setText("Create Delivery/Ordery");
        selectDeliveryOrderyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDeliveryOrderyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(selectConsumatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placeDeliveryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmDeliveryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(selectDeliveryOrderyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectConsumatorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(placeDeliveryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(selectDeliveryOrderyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(confirmDeliveryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        c = (Consumer)(ccbm.getSelectedItem());
        if(c != null){
            CreatesDeliveryUser cdu = new CreatesDeliveryUser();
            mainDesktopPane.add(cdu);
            cdu.show();
        }else{
            if(check()){
                try{
                c = new Consumer();
                c.setName(firstNameField.getText());
                c.setSurname(lastNameField.getText());
                c.setCity(cityField.getText());
                c.setEmail(emailField.getText());
                c.setAdress(adressField.getText());
                c.setPostCode(Integer.parseInt(codeField.getText()));
                c.setTelephone(Integer.parseInt(numberField.getText()));
                cr.create(c);
                CreatesDeliveryUser cdu = new CreatesDeliveryUser();
                mainDesktopPane.add(cdu);
                cdu.show();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                }
             }else{
            JOptionPane.showMessageDialog(this,"Ju lutem selektoni ose plotesoni te gjitha fushat per konsumatoret");
            }
        }
       
    }//GEN-LAST:event_submitButtonActionPerformed

    private void selectDeliveryOrderyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDeliveryOrderyButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        SelectUser su = new SelectUser();
        su.setVisible(true);
    }//GEN-LAST:event_selectDeliveryOrderyButtonActionPerformed

    private void placeDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeDeliveryButtonActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Se pari duhet te selektoni consumatorin ose krijo nje konsumator dhe klikoni \"Submit\"");
    }//GEN-LAST:event_placeDeliveryButtonActionPerformed

    private void confirmDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeliveryButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Se pari duhet te selektoni consumatorin ose krijo nje konsumator dhe klikoni \"Submit\"");
    }//GEN-LAST:event_confirmDeliveryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static Consumer getConsumatori(){
        return c;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectConsumers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectConsumers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectConsumers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectConsumers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectConsumers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CMBConsumer;
    private javax.swing.JTextField adressField;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField codeField;
    private javax.swing.JButton confirmDeliveryButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JTextField numberField;
    private javax.swing.JButton placeDeliveryButton;
    private javax.swing.JButton selectConsumatorButton;
    private javax.swing.JButton selectDeliveryOrderyButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
